# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\x12\x04test\"\xaa\x01\n\x08TEST_MSG\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x15\n\rnum_cpu_cores\x18\x02 \x01(\t\x12\x1a\n\x12\x63pu_usage_per_core\x18\x03 \x01(\t\x12\x14\n\x0ctotal_memory\x18\x04 \x01(\t\x12\x13\n\x0b\x66ree_memory\x18\x05 \x01(\t\x12\x18\n\x10\x61vailable_memory\x18\x06 \x01(\t\x12\x13\n\x0bmemory_used\x18\x07 \x01(\tb\x06proto3')
)




_TEST_MSG = _descriptor.Descriptor(
  name='TEST_MSG',
  full_name='test.TEST_MSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='test.TEST_MSG.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_cpu_cores', full_name='test.TEST_MSG.num_cpu_cores', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_usage_per_core', full_name='test.TEST_MSG.cpu_usage_per_core', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_memory', full_name='test.TEST_MSG.total_memory', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_memory', full_name='test.TEST_MSG.free_memory', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='available_memory', full_name='test.TEST_MSG.available_memory', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_used', full_name='test.TEST_MSG.memory_used', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['TEST_MSG'] = _TEST_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TEST_MSG = _reflection.GeneratedProtocolMessageType('TEST_MSG', (_message.Message,), dict(
  DESCRIPTOR = _TEST_MSG,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.TEST_MSG)
  ))
_sym_db.RegisterMessage(TEST_MSG)


# @@protoc_insertion_point(module_scope)
